### ISSUE TITLE
Build with Java8

### ISSUE THREAD

**Issue by Hugolarson** [JPro-one/JPro-Platform#2]
Hello,
The web-api is build with java 8. Do you think you can the same with this?

**Comment by FlorianKirmaier** [comment]
I guess i could, but currently JPro only work with Java11 and above.
I think, that should also be changed for the WebAPI.

Can you explain a bit, why that would be an advantage? 
If i compile for Java8, then i can no longer define the module - which is the new standard.

**Comment by Hugolarson** [comment]
I understand that JPro only works with Java11 but in my particular case the desktop version of our application runs and compiles on Java8 and need all dependencies java 8 compatible. We have customers that still uses 32 bit windows XP.
Since webapi is still compiled with java 8 I thought to give it a shot :)

**Comment by FlorianKirmaier** [comment]
I think a more elegant solution would be, to just copy the java-file into your project.
It's just one file - so updating it should be easy.
This way it compiles with your Java-Version, and we can keep the module-stuff in this project.

**Comment by ctoabidmaqbool** [comment]
I think a separate branch for jdk 8 should be exists there, because many are still using java 8.

However, I somehow switched all my apps to jdk 17. Still using jdk 8 for Android projects. For jPro.one side (jdk 17)
